### ISSUE TITLE
GeyserMC resource pack?

### ISSUE THREAD

**Issue by pedruhb** [Stoupy51/SimplEnergy#4]
this datapack can be used with geysermc?

**Comment by Stoupy51** [comment]
I.... don't know. I assume that the datapack part will work for sure, but I don't think the resource pack will.
I think they are build differents depending on Java and Bedrock Edition.

But you can apparently convert it: https://learn.microsoft.com/en-us/minecraft/creator/documents/convertingtexturepacks
